---
package_list:
  base:
    - locales
    - lsb-release
    - openssh-server
    - openssl
    - openssh-client
    - sudo
    - systemd-timesyncd
    - whiptail


  basic:
    - apt-transport-https
    - ca-certificates
    - curl
    - git
    - htop
    - python3
    - rsync
    - software-properties-common
    - tree
    - vim-scripts
    - vim-tiny  

  shell:
    - grc
    - zsh
    - tmux

  build:
    - binutils
    - build-essential
    - linux-headers-{{ ansible_kernel }}

  networking:
    - dnsutils
    - ldap-utils
    - nmap
    - tcpdump
    - tcptraceroute
    - traceroute

  networking_basic:
    - dnsutils
    - tcptraceroute
    - traceroute

  dev:
    - astyle
    - colordiff
    - diffstat
    - enscript
    - gdb
    - git
    - golang
    - golang-golang-x-tools
    - highlight
    - jq
    - libffi-dev
    - libgit2-dev
    - libssl-dev
    - mercurial
    - nodejs
    - perl
    - python3
    - python3-dev
    - python3-pip
    - python3-virtualenv
    - ruby
    - ruby-dev
    - subversion

  docker:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin

  java:
    - ant
    - maven
    - openjdk-8-doc
    - openjdk-8-jdk
    - openjdk-8-source

  irc:
    - weechat
    - weechat-plugins

  latex:
    - texlive-base
    - texlive-bibtex-extra
    - texlive-latex-extra
    - texlive-latex-recommended
    - texlive-science
    - texlive-xetex

  arhives:
    - p7zip-full
    - par2
    - unace
    - unrar
    - unzip
    - zip

  misc:
    - lshw
    - memtest86+
    - ncdu
    - p7zip
    - par2
    - pdftk
    - unace
    - unrar
    - unzip
    - wipe
    - zip

  office:
    - gimp
    - gimp-data-extras
    - gimp-plugin-registry
    - google-chrome-stable
    - libreoffice
    - meld
    - shutter

  office_basic:
    - google-chrome-stable

  fonts:
    - fonts-inconsolata

  media:
    - libavcodec-extra
    - libdvdread7
    - mpv
    - vlc

  virtualization:
    - dkms
    - vagrant
    - virtualbox-5.0

  gnome:
    - libgnome-keyring-dev
    - libreoffice-gnome

distro_package_list:
  debian:
    - iptables-persistent
  ubuntu:
    - ufw

python_package_list:
  base: []
  
  basic:
    - pip
    - virtualenv
    - requests

  ansible:
    - Jinja2
    - PyYAML
    - cryptography
    - httplib2
    - paramiko
    - pycrypto
    - simplejson
    - six
    - ansible

  dev:
    - speedtest-cli

  powerline:
    - powerline-status
    - powerline-mem-segment
    - psutil
