---
# Run common role on all instances
- hosts: all
  become: yes
  become_user: root
  gather_facts: yes

  tasks:
    - include_role:
        name: common

    - include_role:
        name: user-setup
      with_items: "{{ superusers | default([]) }}"

- hosts: server
  become: yes
  become_user: root
  gather_facts: yes

  tasks:
    - include_role:
        name: wireguard
      when:
        - wireguard_sever is defined
        - wireguard_sever
