---
- name: apt update
  ansible.builtin.apt:
    update_cache: yes

- name: apt autoclean
  ansible.builtin.apt:
    autoclean: yes

- name: apt autoremove
  ansible.builtin.apt:
    autoremove: yes

- name: restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: restart cron
  ansible.builtin.service:
    name: cron
    state: restarted

- name: restart smtpd
  ansible.builtin.service:
    name: opensmtpd
    state: restarted

- name: restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted