---
- name: apt update
  apt:
    update_cache: yes

- name: apt autoclean
  apt:
    autoclean: yes

- name: apt autoremove
  apt:
    autoremove: yes

- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: restart ntp
  service:
    name: ntp
    state: restarted

- name: restart cron
  service:
    name: cron
    state: restarted

- name: restart smtpd
  service:
    name: opensmtpd
    state: restarted

- name: update iptables
  shell: iptables-restore < /etc/iptables/rules.v4

- name: update ip6tables
  shell: ip6tables-restore < /etc/iptables/rules.v6
