---
- name: install ufw
  ansible.builtin.apt:
    name:
      - ufw
    state: present

- name: ufw (tcp)
  community.general.ufw:
    rule: allow
    port: "{{ item | string }}"
    proto: tcp
  with_items: "{{ open_ports_tcp }}"

- name: ufw (udp)
  community.general.ufw:
    rule: allow
    port: "{{ item | string }}"
    proto: udp
  with_items: "{{ open_ports_udp }}"

- name: set default ufw policies
  community.general.ufw:
    policy: "{{ item.policy }}"
    direction: "{{ item.direction }}"
  with_items:
    - { direction: "incoming", policy: "deny" }
    - { direction: "routed", policy: "deny" }
    - { direction: "outgoing", policy: "allow" }

- name: Enable ufw
  community.general.ufw:
    state: enabled
