---
- name: ubuntu sources
  ansible.builtin.template:
    src: ubuntu-sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - apt update

- name: setup external package repositories
  ansible.builtin.include_tasks: setup-external-repositories.yaml

- name: upgrade existing packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
  notify:
    - apt autoclean
    - apt autoremove

- name: Install software packages (apt)
  ansible.builtin.apt:
    name: "{{ packages | mandatory }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  notify:
    - apt autoclean
    - apt autoremove

- name: Install software packages from source (not using apt)
  ansible.builtin.include_tasks: install-packages-from-src.yaml
  when: install_nonpackaged_software

- name: install snap core
  community.general.snap:
    name: core

- name: ensure snapd is enabled.
  ansible.builtin.systemd:
    name: snapd.socket
    enabled: true
    state: started