---
- name: install openstmpd
  ansible.builtin.apt:
    name:
      - opensmtpd
      - opensmtpd-extras
      - mailutils
    state: present

- name: create opensmtpd configuration directory
  ansible.builtin.file:
    path: /etc/opensmtpd
    state: directory
    owner: root
    group: root
    mode: 0755

- name: host mailname
  ansible.builtin.copy:
    content: "{{ mailname | default(inventory_hostname) }}"
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644
  notify:
    - restart smtpd

- name: relay secrets
  ansible.builtin.copy:
    content: "{{ smtp_profile }} {{ smtp_username }}:{{ smtp_password }}\n"
    dest: /etc/opensmtpd/secrets
    owner: root
    group: opensmtpd
    mode: 0640
  notify:
    - restart smtpd

- name: opensmtpd configuration
  ansible.builtin.template:
    src: smtpd.conf.j2
    dest: /etc/smtpd.conf
    owner: root
    group: root
    mode: 0644
    backup: true
    validate: smtpd -n -f %s
  notify:
    - restart smtpd

- name: enable smtpd
  ansible.builtin.service:
    name: opensmtpd
    enabled: yes
