---
- name: install ansible dependencies
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_distribution == 'Debian'
  with_items:
    - sudo
    - apt-transport-https
    - dirmngr
    - python
    - python-simplejson

- name: install packages from os repositories
  include: install-packages.yaml

- name: install packages via pip
  include: install-pip-packages.yaml

- name: update editor alternatives
  alternatives:
    name: editor
    path: /usr/bin/vim.nox

- name: create user groups
  group:
    name: '{{ item }}'
    state: present
    system: no
  with_items:
    - '{{ admin_groups }}'
    - '{{ user_groups }}'

- name: ssh hardening
  include: ssh-hardening.yaml

- name: set timezone
  timezone:
    name: '{{ host_timezone }}'
  notify:
    - restart ntp
    - restart cron

- name: enable locale
  locale_gen:
    name: '{{ host_locale }}'
    state: present
