---
- name: install ansible dependencies
  apt:
    name:
      - sudo
      - apt-transport-https
      - dirmngr
      - python
      - python-simplejson
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_distribution == 'Debian'


- name: install packages from os repositories
  include: install-packages.yaml

- name: install packages via pip
  include: install-pip-packages.yaml

- name: update editor alternatives
  alternatives:
    name: editor
    path: /usr/bin/vim.nox

- name: create user groups
  group:
    name: '{{ item }}'
    state: present
    system: no
  with_items:
    - '{{ admin_groups }}'
    - '{{ user_groups }}'

- name: ssh hardening
  include: ssh-hardening.yaml

- name: set timezone
  timezone:
    name: '{{ host_timezone }}'
  notify:
    - restart ntp
    - restart cron

- name: enable locale
  locale_gen:
    name: '{{ host_locale }}'
    state: present

- name: set hostname
  hostname:
    name: '{{ ansible_host }}'

- name: set dns resolvers
  template:
    src: templates/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  with_items: '{{ dns_resolvers }}'
  when: dns_resolvers | length > 0

- name: create iptables rules
  template:
    src: templates/iptables.conf.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - update iptables

- name: create ip6tables rules
  template:
    src: templates/ip6tables.conf.j2
    dest: /etc/iptables/rules.v6
    owner: root
    group: root
    mode: 0644
  notify:
    - update ip6tables

- name: filesystem mount points
  mount:
    path: '{{ item.path }}'
    src: '{{ item.src }}'
    fstype: '{{ item.fstype }}'
    state: mounted
    backup: yes
  with_items: '{{ fs_mounts }}'

- name: install slacktee for alerts
  include: install-slacktee.yaml
