---
- name: Create a directory for armored gpg keys
  ansible.builtin.file:
    path: /usr/share/gpg-keyrings/
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: install docker
  block:
    - name: download docker gpg key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/gpg-keyrings/docker-archive-keyring.gpg.asc
        checksum: sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570
    
    - name: de-armor gpg key
      ansible.builtin.command:  gpg --output /usr/share/keyrings/docker-archive-keyring.gpg --dearmor /usr/share/gpg-keyrings/docker-archive-keyring.gpg.asc
      no_log: true
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg
    
    - name: add docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: true

  when: '"docker-ce" in packages'