---
- name: set ssh protocol to 2
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[P|p]rotocol'
    insertafter: '^#[\s]*[P|p]rotocol|^#[\s]*[P|p]ort'
    line: 'Protocol 2'
    state: present
    create: no
    backup: yes
    validate: sshd -T -f %s
  notify: restart ssh

- name: set ssh to port
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[P|p]ort'
    insertafter: '^#[\s]*[P|p]ort'
    line: 'Port 22'
    state: present
    create: no
    backup: yes
    validate: sshd -T -f %s
  notify: restart ssh

- name: disable root login via ssh
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[P|p]ermit[R|r]oot[L|l]ogin'
    insertafter: '^#[\s]*[P|p]ermit[R|r]oot[L|l]ogin'
    line: 'PermitRootLogin no'
    state: present
    create: no
    backup: yes
    validate: sshd -T -f %s
  notify: restart ssh

- name: disable password authentication
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[P|p]assword[A|a]uthentication'
    insertafter: '^#[\s]*[P|p]assword[A|a]uthentication'
    line: 'PasswordAuthentication no'
    state: present
    create: no
    backup: yes
    validate: sshd -T -f %s
  notify: restart ssh

- name: disable challenge response authentication
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[C|c]hallenge[R|r]esponse[A|a]uthentication'
    insertafter: '^#[\s]*[C|c]hallenge[R|r]esponse[A|a]uthentication'
    line: 'ChallengeResponseAuthentication no'
    state: present
    create: no
    backup: yes
  notify: restart ssh

- name: disable user-environment options
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[P|p]ermit[U|u]ser[E|e]nvironment'
    insertafter: '^#^[P|p]ermit[U|u]ser[E|e]nvironment'
    line: 'PermitUserEnvironment no'
    state: present
    create: no
    backup: yes
    validate: sshd -T -f %s
  notify: restart ssh

- name: set ClientAliveInterval to 5 minutes
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[C|c]lient[A|a]live[I|i]nterval'
    insertafter: '^#[C|c]lient[A|a]live[I|i]nterval'
    line: 'ClientAliveInterval 300'
    state: present
    create: no
    backup: yes
    validate: sshd -T -f %s
  notify: restart ssh

- name: set ClientAliveCountMax to 3
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[C|c]lient[A|a]live[C|c]ount[M|m]ax'
    insertafter: '^#[C|c]lient[A|a]live[C|c]ount[M|m]ax'
    line: 'ClientAliveCountMax 3'
    state: present
    create: no
    backup: yes
    validate: sshd -T -f %s
  notify: restart ssh

- name: disable x11 forwarding
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[X|x]11[F|f]orwarding'
    insertafter: '^#[X|x]11[F|f]orwarding'
    line: 'X11Forwarding no'
    state: present
    create: no
    backup: yes
    validate: sshd -T -f %s
  notify: restart ssh

- name: ssh allowgroup configuration
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^AllowGroups '
    insertafter: '^#[\s]*[A|a]llow[G|g]roups'
    line: 'AllowGroups {{ (admin_groups | union(user_groups)) | join(" ") }}'
    create: no
    backup: yes
    validate: sshd -T -f %s
  notify:
    - restart ssh

- name: harden key exchange
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[K|k]ex[A|a]lgorithms'
    insertafter: '^#[K|k]ex[A|a]lgorithms'
    line: 'KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256'
    state: present
    create: no
    backup: yes
  notify: restart ssh

- name: harden symmetric ciphers
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[C|c]iphers'
    insertafter: '^#[C|c]iphers'
    line: 'Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'
    state: present
    create: no
    backup: yes
  notify: restart ssh

- name: harden message authentication codes
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[M|m]ACs'
    insertafter: '^#[M|m]ACs'
    line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'
    state: present
    create: no
    backup: yes
    validate: sshd -T -f %s
  notify: restart ssh

- name: specify the order of hostkey algorithms
  ansible.builtin.blockinfile:
    path: /etc/ssh/sshd_config
    insertafter: '^#[H|h]ost[K|k]ey'
    block: |
      HostKey /etc/ssh/ssh_host_ed25519_key
      HostKey /etc/ssh/ssh_host_rsa_key
      HostKey /etc/ssh/ssh_host_ecdsa_key
    state: present
    create: no
    backup: yes
    validate: sshd -T -f %s
  notify: restart ssh