---
- name: enable unstable repositories for wireguard
  apt_repository:
    repo: '{{ item }}'
    state: present
    filename: unstable-wireguard
    mode: 0644
    update_cache: yes
  with_items:
    - 'deb http://deb.debian.org/debian/ unstable main'

- name: limit pin-priority of unstable repository
  copy:
    src: limit-unstable
    dest: /etc/apt/preferences.d/limit-unstable
    owner: root
    group: root
    mode: 0644

- name: increase pin-priority of wireguard packages in unstable repository
  copy:
    src: wireguard-unstable
    dest: /etc/apt/preferences.d/wireguard-unstable
    owner: root
    group: root
    mode: 0644

- name: install wireguard
  apt:
    name:
      - wireguard
      - wireguard-dkms
      - wireguard-tools
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_distribution == 'Debian'

- name: enable ipv4 packet forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes

- name: enable ipv4 packet forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes

- name: create wireguard configuration path
  file:
    path: /etc/wireguard
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create wireguard private key
  shell:
    cmd: wg genkey > /etc/wireguard/wg-private.key
    creates: /etc/wireguard/wg-private.key
  notify:
    - restart wg0

- name: set file permissions for wireguard private key
  file:
    path: /etc/wireguard/wg-private.key
    owner: root
    group: root
    mode: 0600

- name: create wireguard public key
  shell:
    cmd: cat /etc/wireguard/wg-private.key | wg pubkey > /etc/wireguard/wg-public.key
    creates: /etc/wireguard/wg-public.key
  notify:
    - restart wg0

- name: set file permissions for wireguard public key
  file:
    path: /etc/wireguard/wg-public.key
    owner: root
    group: root
    mode: 0644

- name: obtain private key
  slurp:
    src: /etc/wireguard/wg-private.key
  register: wireguard_private_key_reg

- name: wireguard configuration file
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600
  vars:
    - wireguard_private_key: "{{ wireguard_private_key_reg['content'] | b64decode }}"
  notify:
    - restart wg0

- name: enable and start wireguard service
  service:
    name: wg-quick@wg0
    state: started
    enabled: yes
